version: '3.8'
services:
  frontend:
    build:
      context: ./accountflow-front
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./accountflow-front:/app

  backend:
    build:
      context: ./accountflow
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - DJANGO_SETTINGS_MODULE=accountflow.config.settings
    volumes:
      - ./accountflow:/code
    depends_on:
      - frontend
