services:
  frontend:
    build:
      context: ./accountflow-front
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./accountflow-front:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=1
      - WATCHPACK_POLLING=true
      - NEXT_TELEMETRY_DISABLED=1

  backend:
    build:
      context: ./accountflow-api
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.django
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - TZ=America/Sao_Paulo
    volumes:
      - ./accountflow-api:/code
    restart: unless-stopped
